name: Lint, Build, and Push
on:
  push:
    branches-ignore:
      - none

jobs:
  build:
    name: Build and Push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Lint
        run: make lint

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Get changed files
        id: changed_files
        uses: tj-actions/changed-files@v37

      - name: List all changed files
        run: |
          for file in ${{ steps.changed_files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done

      - name: Push to DockerHub
        run: for folder in ${{ steps.changed_folders.outputs.folders }}; do make push-$folder; done
